-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 23:40:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema series_e_filmes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema series_e_filmes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `series_e_filmes` DEFAULT CHARACTER SET utf8 ;
USE `series_e_filmes` ;

-- -----------------------------------------------------
-- Table `series_e_filmes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series_e_filmes`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `sobrenome` VARCHAR(150) NULL,
  `nomeUsuario` VARCHAR(200) NULL,
  `senha` VARCHAR(32) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series_e_filmes`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series_e_filmes`.`filme` (
  `idfilme` INT NOT NULL AUTO_INCREMENT,
  `idTmdb` INT NULL,
  `titulo` VARCHAR(300) NULL,
  `situacao` TINYINT NULL,
  `lista` TINYINT NULL,
  `url_capa` VARCHAR(34) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idfilme`),
  INDEX `fk_filme_usuario_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_filme_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `series_e_filmes`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series_e_filmes`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series_e_filmes`.`serie` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(300) NULL,
  `idTmdb` INT NULL,
  `situacao` INT NULL,
  `lista` TINYINT NULL,
  `url_capa` VARCHAR(34) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idserie`),
  INDEX `fk_serie_usuario1_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_serie_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `series_e_filmes`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series_e_filmes`.`temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series_e_filmes`.`temporada` (
  `idtemporada` INT NOT NULL AUTO_INCREMENT,
  `idTmdbTemp` INT NULL,
  `tituloTemp` VARCHAR(300) NULL,
  `situacao` TINYINT NULL,
  `serie_idserie` INT NOT NULL,
  PRIMARY KEY (`idtemporada`),
  INDEX `fk_temporada_serie1_idx` (`serie_idserie` ASC) ,
  CONSTRAINT `fk_temporada_serie1`
    FOREIGN KEY (`serie_idserie`)
    REFERENCES `series_e_filmes`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series_e_filmes`.`episodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series_e_filmes`.`episodio` (
  `idepisodio` INT NOT NULL AUTO_INCREMENT,
  `tituloEp` VARCHAR(45) NULL,
  `situacao` TINYINT NULL,
  `temporada_idtemporada` INT NOT NULL,
  PRIMARY KEY (`idepisodio`),
  INDEX `fk_episodio_temporada1_idx` (`temporada_idtemporada` ASC) ,
  CONSTRAINT `fk_episodio_temporada1`
    FOREIGN KEY (`temporada_idtemporada`)
    REFERENCES `series_e_filmes`.`temporada` (`idtemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
